Config = {}

Config.Healing = 3 -- // If this is 0, then its disabled.. Default: 3.. That means, if a person lies in a bed, then he will get 1 health every 3 seconds.

-- [[ https://docs.fivem.net/game-references/controls/ ]]

Config.Text = {
	SitOnChair = '~INPUT_PICKUP~ para sentarse en la silla',
	SitOnBed = '~INPUT_PICKUP~ para sentarte en la camilla',
	LieOnBed = '~INPUT_PICKUP~ para acostarte',
	SwitchBetween = '~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ cambiar entre',
	Standup = '¡~INPUT_VEH_DUCK~ para levantarte!',
}

Config.objects = {
	ButtonToSitOnChair = 38, -- // --  E -- // https://docs.fivem.net/game-references/controls/
	ButtonToLayOnBed = 38, -- // -- E -- // https://docs.fivem.net/game-references/controls/
	ButtonToStandUp = 73, -- // -- X -- // https://docs.fivem.net/game-references/controls/
	SitAnimation = {anim='PROP_HUMAN_SEAT_CHAIR_MP_PLAYER'},
	BedBackAnimation = {dict='anim@gangops@morgue@table@', anim='ko_front'},
	BedStomachAnimation = {dict='amb@lo_res_idles@', anim='lying_face_down_lo_res_base'},    --{anim='WORLD_HUMAN_SUNBATHE'},
	BedSitAnimation = {anim='WORLD_HUMAN_PICNIC'},
	bedlocations = {
		{object=GetHashKey("v_med_bed2"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true},
		{object=GetHashKey("v_med_bed1"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true},
		{object=GetHashKey("v_med_emptybed"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=90.0, bed=true},
		{object=-1182962909, verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=90.0, bed=true}

	},
	locations = {
	{object=GetHashKey("v_serv_ct_chair02"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=168.0, bed=false},
	{object=GetHashKey("prop_off_chair_04"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
	{object=GetHashKey("prop_off_chair_03"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
	{object=GetHashKey("prop_off_chair_05"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
	{object=GetHashKey("v_club_officechair"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
	{object=GetHashKey("v_ilev_leath_chr"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
	{object=GetHashKey("v_corp_offchair"), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
	{object=GetHashKey("Prop_Off_Chair_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_01a"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_01b"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_01c"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_03"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_04"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_05"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_06"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_09"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_10"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_bench_11"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_fib_3b_bench"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_ld_bench01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_wait_bench_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("hei_prop_heist_off_chair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("hei_prop_hei_skid_chair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_01a"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_01b"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_03"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_04a"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_04b"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_05"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_06"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_08"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_09"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chair_10"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_chateau_chair_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_clown_chair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_cs_office_chair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_direct_chair_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_direct_chair_02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_gc_chair02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_off_chair_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_off_chair_03"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_off_chair_04"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_off_chair_04b"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_off_chair_04_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_off_chair_05"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_old_deck_chair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_old_wood_chair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_rock_chair_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_skid_chair_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_skid_chair_02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_skid_chair_03"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_sol_chair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_wheelchair_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_wheelchair_01_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_armchair_01_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_clb_officechair_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_dinechair_01_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_ilev_p_easychair_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_soloffchair_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_yacht_chair_01_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_club_officechair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_corp_bk_chair3"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_corp_cd_chair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_corp_offchair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_chair02_ped"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_p_easychair"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ret_gc_chair03"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_ld_farm_chair01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_table_04_chr"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_table_05_chr"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_table_06_chr"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_leath_chr"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_table_01_chr_a"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=0.0, direction=180.0, bed=false},
	{object=GetHashKey("prop_table_01_chr_b"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_table_02_chr"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_table_03b_chr"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_table_03_chr"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_torture_ch_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_fh_dineeamesa"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_fh_kitchenstool"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_tort_stool"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_fh_kitchenstool"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_fh_kitchenstool"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("hei_prop_yah_seat_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("hei_prop_yah_seat_02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("hei_prop_yah_seat_03"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_waiting_seat_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_yacht_seat_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_yacht_seat_02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_yacht_seat_03"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_hobo_seat_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_rub_couch01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("miss_rub_couch_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_ld_farm_couch01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_ld_farm_couch02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_rub_couch03"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_rub_couch04"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_lev_sofa_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_res_sofa_l_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_v_med_p_sofa_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("p_yacht_sofa_01_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_m_sofa"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_res_tre_sofa_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_tre_sofa_mess_a_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_tre_sofa_mess_b_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_tre_sofa_mess_c_s"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_roller_car_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("prop_roller_car_02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_ph_bench"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("ex_prop_offchair_exec_04"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("ex_prop_offchair_exec_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("vw_prop_vw_offchair_02"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("vw_prop_casino_chair_01a"), verticalOffsetX=0.0, verticalOffsetY=0.2, verticalOffsetZ=-0.75, direction=360.0, bed=false},
	{object=GetHashKey("vw_prop_casino_track_chair_01"), verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
	{object=GetHashKey("ba_prop_battle_club_chair_02"), verticalOffsetX = 0.1, verticalOffsetY = 0.0, verticalOffsetZ = 0.0, direction=180.0, bed=false},
	{object=GetHashKey("v_res_m_l_chair1"), verticalOffsetX = 0.0, verticalOffsetY = 0.0, verticalOffsetZ = -0.5, direction=180.0, bed=false},
	{object=GetHashKey("v_ilev_m_dinechair"), verticalOffsetX = -0.5, verticalOffsetY = 0.0, verticalOffsetZ = 0.0, direction=180.0, bed=false},
	{object=GetHashKey("v_ret_chair"), verticalOffsetX = -0.5, verticalOffsetY = 0.0, verticalOffsetZ = 0.0, direction=180.0, bed=false},
	{object=GetHashKey("v_ret_gc_chair02"), verticalOffsetX = 0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=180.0, bed=false},
	{object=GetHashKey("v_med_wickerchair1"), verticalOffsetX = 0, verticalOffsetY = 0.0, verticalOffsetZ = 0.0, direction=0.0, bed=false},
	{object=GetHashKey("v_med_whickchair2"), verticalOffsetX = 0, verticalOffsetY = 0.0, verticalOffsetZ = 0.0, direction=0.0, bed=false},
	{object=-853526657, verticalOffsetX = 0, verticalOffsetY = 0.0, verticalOffsetZ = 0.2, direction=180.0, bed=false},
 }
}